# Form implementation generated from reading ui file 'admin_menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Admin_menu_MainWindow(object):
    def setupUi(self, Admin_menu_MainWindow):
        Admin_menu_MainWindow.setObjectName("Admin_menu_MainWindow")
        Admin_menu_MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=Admin_menu_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 791, 581))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.werhere_image_label = QtWidgets.QLabel(parent=self.frame)
        self.werhere_image_label.setGeometry(QtCore.QRect(200, 0, 451, 131))
        self.werhere_image_label.setText("")
        self.werhere_image_label.setPixmap(QtGui.QPixmap("../../../../Downloads/IMG-20240507-WA0026.jpg"))
        self.werhere_image_label.setObjectName("werhere_image_label")
        self.Check_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.Check_pushButton.setGeometry(QtCore.QRect(90, 180, 75, 24))
        self.Check_pushButton.setStyleSheet("\n"
"QPushButton:hover {\n"
"\n"
"                  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,157, 255, 255), stop:1 rgba(30, 206, 255, 255));\n"
"                  color: rgb(255, 255, 255);\n"
"                  }\n"
"\n"
"QPushButton:pressed {\n"
"                    background-color: rgb(255, 255, 255);\n"
"                    color: rgb(0, 0, 255);\n"
"                    }\n"
"")
        self.Check_pushButton.setObjectName("Check_pushButton")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(220, 170, 75, 24))
        self.pushButton.setStyleSheet("\n"
"QPushButton:hover {\n"
"\n"
"                  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,157, 255, 255), stop:1 rgba(30, 206, 255, 255));\n"
"                  color: rgb(255, 255, 255);\n"
"                  }\n"
"\n"
"QPushButton:pressed {\n"
"                    background-color: rgb(255, 255, 255);\n"
"                    color: rgb(0, 0, 255);\n"
"                    }\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 170, 75, 24))
        self.pushButton_3.setStyleSheet("\n"
"QPushButton:hover {\n"
"\n"
"                  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,157, 255, 255), stop:1 rgba(30, 206, 255, 255));\n"
"                  color: rgb(255, 255, 255);\n"
"                  }\n"
"\n"
"QPushButton:pressed {\n"
"                    background-color: rgb(255, 255, 255);\n"
"                    color: rgb(0, 0, 255);\n"
"                    }\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 180, 75, 24))
        self.pushButton_4.setStyleSheet("\n"
"QPushButton:hover {\n"
"\n"
"                  background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0,157, 255, 255), stop:1 rgba(30, 206, 255, 255));\n"
"                  color: rgb(255, 255, 255);\n"
"                  }\n"
"\n"
"QPushButton:pressed {\n"
"                    background-color: rgb(255, 255, 255);\n"
"                    color: rgb(0, 0, 255);\n"
"                    }\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(70, 260, 651, 171))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        Admin_menu_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Admin_menu_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Admin_menu_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Admin_menu_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Admin_menu_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Admin_menu_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Admin_menu_MainWindow)

    def retranslateUi(self, Admin_menu_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Admin_menu_MainWindow.setWindowTitle(_translate("Admin_menu_MainWindow", "MainWindow"))
        self.Check_pushButton.setText(_translate("Admin_menu_MainWindow", "Event Check"))
        self.pushButton.setText(_translate("Admin_menu_MainWindow", "Send Mail"))
        self.pushButton_3.setText(_translate("Admin_menu_MainWindow", "Back "))
        self.pushButton_4.setText(_translate("Admin_menu_MainWindow", "Exit"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Admin_menu_MainWindow", "Event Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Admin_menu_MainWindow", "Nieuwe kolom"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Admin_menu_MainWindow", "Begin Time"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Admin_menu_MainWindow", "Orginizator mail"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Admin_menu_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Admin_menu_MainWindow()
    ui.setupUi(Admin_menu_MainWindow)
    Admin_menu_MainWindow.show()
    sys.exit(app.exec())
